version: "2.3"
services:
  tf:
    build: ./
    runtime: nvidia
    volumes:
      - ../../:/mnist-Grad-CAM
    ports:
      - 18800:18800
    working_dir: /mnist-Grad-CAM
    command: 'tail -f /dev/null'